// sample data
const sampleListings = [
  {
    title: "Luxury Apartment in Bandra",
    description:
      "Stylish sea-facing apartment in the heart of Bandra with modern amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1080&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1800,
    location: "Mumbai",
    country: "India",
    category: "Apartments",
  },
  {
    title: "City View Apartment in Bangalore",
    description: "Modern apartment close to IT parks and nightlife.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1400,
    location: "Bangalore",
    country: "India",
    category: "Apartments",
  },
  {
    title: "5-Star Hotel in Dubai Marina",
    description: "Luxury stay with skyline views and world-class services.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1629577358348-6a9ab759dc74?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 3000,
    location: "Dubai",
    country: "UAE",
    category: "Hotels",
  },
  {
    title: "Boutique Hotel in Paris",
    description: "Romantic hotel near Eiffel Tower with elegant interiors.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1672097247893-4f8660247b1f?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2800,
    location: "Paris",
    country: "France",
    category: "Hotels",
  },
  {
    title: "Beach Resort in Goa",
    description: "Relax at this luxury beach resort with private beach access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1623718649591-311775a30c43?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2200,
    location: "Goa",
    country: "India",
    category: "Resorts",
  },
  {
    title: "Island Resort in Maldives",
    description: "Overwater villas with crystal clear ocean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 5000,
    location: "Male",
    country: "Maldives",
    category: "Resorts",
  },
  {
    title: "Private Villa in Lonavala",
    description: "Luxury villa with pool and mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2600,
    location: "Lonavala",
    country: "India",
    category: "Villas",
  },
  {
    title: "Sea View Villa in Bali",
    description: "Beautiful villa overlooking the ocean with private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=1332&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 3200,
    location: "Bali",
    country: "Indonesia",
    category: "Villas",
  },
  {
    title: "Hilltop Cabin in Manali",
    description: "Cozy wooden cabin surrounded by snow-capped mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1704712507119-863ffb0310d4?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1100,
    location: "Manali",
    country: "India",
    category: "Cabins",
  },
  {
    title: "Forest Cabin in Canada",
    description: "Peaceful retreat in the middle of nature.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585516404887-d8ecacac8c6e?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1300,
    location: "Vancouver",
    country: "Canada",
    category: "Cabins",
  },
  {
    title: "Riverside Cottage in Coorg",
    description:
      "Peaceful cottage surrounded by coffee plantations with a private veranda overlooking the river.",
    image: {
      filename: "coorg_cottage",
      url: "https://images.unsplash.com/photo-1625853175523-ed5da070d32f?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2500,
    location: "Coorg, Karnataka",
    country: "India",
    category: "Cottages",
  },
  {
    title: "Lake Cottage in Udaipur",
    description: "Traditional cottage with lake-facing balcony.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1722432280301-b892780cbd28?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1400,
    location: "Udaipur",
    country: "India",
    category: "Cottages",
  },
  {
    title: "Jungle Treehouse in Kerala",
    description: "Stay among treetops in this eco-friendly treehouse.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1744833467038-045ae9880cee?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1200,
    location: "Wayanad",
    country: "India",
    category: "TreeHouses",
  },
  {
    title: "Rainforest Treehouse in Costa Rica",
    description: "Unique treehouse stay surrounded by rainforest.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1604004218771-05c55db4f9f4?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1800,
    location: "Monteverde",
    country: "Costa Rica",
    category: "TreeHouses",
  },
  {
    title: "Luxury Houseboat in Alleppey",
    description: "Traditional Kerala houseboat with modern luxury.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1720445821834-1db9c765cb82?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2000,
    location: "Alleppey",
    country: "India",
    category: "HouseBoats",
  },
  {
    title: "Canal Houseboat in Amsterdam",
    description: "Romantic stay on Amsterdam canals.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2300,
    location: "Amsterdam",
    country: "Netherlands",
    category: "HouseBoats",
  },
  {
    title: "Luxury Glamping",
    description: "Enjoy luxury tents under the stars in the peaceful desert.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1632367294096-4e77d53c4ae9?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1400,
    location: "Jaisalmer",
    country: "India",
    category: "GlampingSites",
  },
  {
    title: "Forest Glamping Escape",
    description: "Comfortable tents surrounded by dense forest and wildlife.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1576176539998-0237d1ac6a85?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1300,
    location: "Bali",
    country: "Indonesia",
    category: "GlampingSites",
  },
  {
    title: "Private Room in City Center",
    description: "Affordable private room near all major attractions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 700,
    location: "Delhi",
    country: "India",
    category: "Rooms",
  },
  {
    title: "Cozy Room Near Metro",
    description: "Perfect for solo travelers and students.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1157&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 650,
    location: "Berlin",
    country: "Germany",
    category: "Rooms",
  },
  {
    title: "Peaceful Guest Room in Suburbs",
    description: "Quiet stay with homely environment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1718071101959-34de414a0e0f?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 800,
    location: "Pune",
    country: "India",
    category: "GuestRooms",
  },
  {
    title: "Elegant Guest Room in Villa",
    description: "Comfortable guest room with garden view.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1632210702485-e1841e30752a?q=80&w=1332&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 900,
    location: "Nice",
    country: "France",
    category: "GuestRooms",
  },
  {
    title: "Backpackers City Hostel",
    description: "Budget friendly hostel for travelers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1709805619372-40de3f158e83?q=80&w=1195&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 400,
    location: "Bangkok",
    country: "Thailand",
    category: "Hostels",
  },
  {
    title: "Modern Youth Hostel",
    description: "Meet travelers from all over the world.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1623625434462-e5e42318ae49?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 450,
    location: "Barcelona",
    country: "Spain",
    category: "Hostels",
  },
  {
    title: "Organic Farm Stay Experience",
    description: "Live close to nature and farm life.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600457008548-8a153e914616?q=80&w=1174&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1000,
    location: "Nashik",
    country: "India",
    category: "FarmStays",
  },
  {
    title: "Countryside Farm Cottage",
    description: "Relax in green fields and fresh air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1617859428921-e21f9f8fac0f?q=80&w=1168&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1100,
    location: "Tuscany",
    country: "Italy",
    category: "FarmStays",
  },
  {
    title: "Traditional Ryokan Stay",
    description: "Experience Japanese culture with tatami rooms.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1709742877524-68adf97ef4a6?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2200,
    location: "Kyoto",
    country: "Japan",
    category: "Ryokans",
  },
  {
    title: "Mountain View Ryokan",
    description: "Relax in hot springs with mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1643071285725-297564074708?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2400,
    location: "Hakone",
    country: "Japan",
    category: "Ryokans",
  },
  {
    title: "Arctic Glass Igloo Stay",
    description: "Watch northern lights from your bed.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1652601373869-3fae01d76f8e?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 3000,
    location: "Chennai, Tamil Nadu",
    country: "India",
    category: "Artic",
  },
  {
    title: "Snow Cabin in Arctic Circle",
    description: "Unique snow-covered cabin experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1611582785023-91a3c0999d93?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2800,
    location: "Manali, Himachal Pradesh",
    country: "India",
    category: "Artic",
  },
  {
    title: "Traditional Moroccan Riad",
    description: "Beautiful courtyard stay in old city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1540396515873-dd778f7679e7?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 1800,
    location: "Marrakech",
    country: "Morocco",
    category: "Riads",
  },
  {
    title: "Luxury Riad with Pool",
    description: "Authentic Moroccan stay with modern comfort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1628642004970-1da51c8c7dec?q=80&w=939&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    price: 2000,
    location: "Fes",
    country: "Morocco",
    category: "Riads",
  },
];

module.exports = { data: sampleListings };
